### ISSUE TITLE
Use of `PANTS_SHA` reexecutes some bootstrapping logic on each run

### ISSUE THREAD

**Issue by stuhood** [pantsbuild/scie-pants#173]
When `PANTS_SHA` is in use, a series of downloading lines flash by on every invoke.

**Comment by stuhood** [comment]
It looks like that is because we fetch a version file for the sha inside of `scie-pants`'s `src/main.rs`... seems like that could be converted into a binding calculated by the bootstrap step?

**Comment by jsirois** [comment]
But that only runs due to this:
https://github.com/pantsbuild/scie-pants/blob/92a64f2992ad31d9b7fef221a569ada78afe1246/src/main.rs#L251-L258

So that's the bug. The assumption is no PANTS_VERSION means no Pants version and the user must e prompted to set up a new repo. Here there is a Pants version via `PANTS_SHA`.
